apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-agent
  labels:
    managed-by: last9
  namespace: last9-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-agent
  namespace: last9-monitoring
  labels:
    managed-by: last9
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-agent
  labels:
    managed-by: last9
  namespace: last9-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-agent
subjects:
  - kind: ServiceAccount
    name: prometheus-agent
    namespace: last9-monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-agent
  labels:
    component: prometheus-agent
    managed-by: last9
  namespace: last9-monitoring
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus-agent
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
  labels:
    app: prometheus-agent
    managed-by: last9
  namespace: last9-monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus-agent
  serviceMonitorSelector:
    matchLabels:
      managed-by: last9
  podMonitorSelector:
    matchLabels:
      managed-by: last9
  remoteWrite:
    - url: <levitate_remote_wrote_url>
      basicAuth:
        username:
          name: levitate-secrets
          key: username
        password:
          name: levitate-secrets
          key: password
  externalLabels:
    via_cluster: 'minikube' # Change this as per what is appropriate
